alter session SET NLS_DATE_FORMAT='dd/mm/rr hh24:mi:ss';

SELECT a.SID, a.SERIAL# serial, spid,SOFAR, TOTALWORK,
ROUND(SOFAR/TOTALWORK*100,2) "%_COMPLETE", s.CLIENT_INFO
FROM V$SESSION_LONGOPS a,V$PROCESS p, V$SESSION s
WHERE a.sid=s.sid AND p.ADDR = s.PADDR
AND CLIENT_INFO LIKE 'rman%'
AND OPNAME LIKE 'RMAN%'
AND OPNAME NOT LIKE '%aggregate%'
AND TOTALWORK != 0
AND SOFAR <> TOTALWORK;



